import type { World } from "../lib/world";
import type { BoxerFull } from "../lib/types";

/**
 * Plain-English fighter searches ("fighters with more than 10 losses", "heavyweights with a losing record", "taller than 190 cm"), each with the plain truth
 * about the league worked out from the fighters' own numbers: the search must return exactly the fighters the sentence describes, no more and no fewer. A search
 * that ignores part of the sentence, or reads a number as the wrong thing, returns the wrong set; that is what this measures. Fighters with no fight are not
 * in a search, and a fact the data does not have never satisfies a condition on it.
 */
export interface NlCase { q: string; kind: string; group: "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J"; truth: (b: BoxerFull, w: World) => boolean }

const known = (v: number | null, f: (v: number) => boolean) => v !== null && f(v);
/** The fights that count in a record, oldest first. */
const record = (b: BoxerFull, w: World) => (w.boutsByBoxer.get(b.id) ?? []).filter((x) => !x.upcoming && x.method !== null && x.method !== "NC");
const back = (w: World, n: number, unit: "months" | "years" | "weeks"): string => { const d = new Date(w.today + "T12:00:00Z"); if (unit === "months") d.setUTCMonth(d.getUTCMonth() - n); else if (unit === "years") d.setUTCFullYear(d.getUTCFullYear() - n); else d.setUTCDate(d.getUTCDate() - 7 * n); return d.toISOString().slice(0, 10); };

export function nlCases(): NlCase[] {
  const c = (group: NlCase["group"], kind: string, q: string, truth: NlCase["truth"]): NlCase => ({ q, kind, group, truth });
  return [
    // A: the comparisons the search was meant to read
    c("A", "wins, at least", "fighters with at least 20 wins", (b) => b.wins >= 20),
    c("A", "wins, N+", "fighters with 25+ wins", (b) => b.wins >= 25),
    c("A", "knockouts, at least", "fighters with at least 8 KOs", (b) => b.kos >= 8),
    c("A", "knockouts, N or more", "boxers with 10 or more knockouts", (b) => b.kos >= 10),
    c("A", "age, over", "boxers over 35", (b) => known(b.age, (a) => a >= 36)),
    c("A", "age, under", "boxers under 25", (b) => known(b.age, (a) => a < 25)),
    c("A", "reach, over", "fighters with a reach over 185", (b) => known(b.reachCm, (r) => r > 185)),
    c("A", "undefeated", "undefeated fighters", (b) => b.losses === 0),
    // B: other comparisons and measures, and the plain-words ones
    c("B", "losses, more than", "fighters with more than 10 losses", (b) => b.losses > 10),
    c("B", "losses, at least", "fighters with at least 8 losses", (b) => b.losses >= 8),
    c("B", "losses, fewer than", "fighters with fewer than 3 losses", (b) => b.losses < 3),
    c("B", "losses, exactly", "fighters with exactly 4 losses", (b) => b.losses === 4),
    c("B", "losses, at most", "fighters with at most 2 losses", (b) => b.losses <= 2),
    c("B", "losses, none", "fighters with no losses", (b) => b.losses === 0),
    c("B", "losses, never", "fighters who have never lost", (b) => b.losses === 0),
    c("B", "losses, under", "boxers with under 5 losses", (b) => b.losses < 5),
    c("B", "wins, more than", "fighters with more than 25 wins", (b) => b.wins > 25),
    c("B", "wins, fewer than", "fighters with fewer than 10 wins", (b) => b.wins < 10),
    c("B", "wins, between", "fighters with between 15 and 25 wins", (b) => b.wins >= 15 && b.wins <= 25),
    c("B", "wins, to", "fighters with 20 to 30 wins", (b) => b.wins >= 20 && b.wins <= 30),
    c("B", "wins, exactly", "fighters with exactly 12 wins", (b) => b.wins === 12),
    c("B", "wins, under", "fighters with under 15 wins", (b) => b.wins < 15),
    c("B", "knockouts, more than", "boxers with more than 10 knockouts", (b) => b.kos > 10),
    c("B", "knockouts, fewer than", "boxers with fewer than 5 knockouts", (b) => b.kos < 5),
    c("B", "knockouts, none", "fighters with no knockouts", (b) => b.kos === 0),
    c("B", "knockouts, never won by", "fighters who never won by knockout", (b) => b.kos === 0),
    c("B", "knockouts, between", "fighters with between 5 and 10 KOs", (b) => b.kos >= 5 && b.kos <= 10),
    c("B", "fights, more than", "fighters who have fought more than 30 times", (b) => b.bouts > 30),
    c("B", "fights, more than (fights)", "fighters with more than 30 fights", (b) => b.bouts > 30),
    c("B", "fights, fewer than", "boxers with fewer than 10 fights", (b) => b.bouts < 10),
    c("B", "fights, at least", "boxers with at least 25 bouts", (b) => b.bouts >= 25),
    c("B", "fights, or fewer", "boxers with 10 or fewer fights", (b) => b.bouts <= 10),
    c("B", "age, to", "fighters aged 30 to 35", (b) => known(b.age, (a) => a >= 30 && a <= 35)),
    c("B", "age, between", "fighters between 25 and 30 years old", (b) => known(b.age, (a) => a >= 25 && a <= 30)),
    c("B", "age, or older", "boxers 36 or older", (b) => known(b.age, (a) => a >= 36)),
    c("B", "age, younger than", "boxers younger than 28", (b) => known(b.age, (a) => a < 28)),
    c("B", "height, taller than", "fighters taller than 185 cm", (b) => known(b.heightCm, (h) => h > 185)),
    c("B", "height, shorter than", "fighters shorter than 170 cm", (b) => known(b.heightCm, (h) => h < 170)),
    c("B", "height, at least", "fighters at least 190 cm tall", (b) => known(b.heightCm, (h) => h >= 190)),
    c("B", "height, feet", "fighters over 6 feet", (b) => known(b.heightCm, (h) => h > 182.88)),
    c("B", "reach, at least", "boxers with a reach of at least 190", (b) => known(b.reachCm, (r) => r >= 190)),
    c("B", "reach, under", "boxers with a reach under 175", (b) => known(b.reachCm, (r) => r < 175)),
    c("B", "record, winning", "fighters with a winning record", (b) => b.wins > b.losses),
    c("B", "record, losing", "fighters with a losing record", (b) => b.losses > b.wins),
    c("B", "turned pro in", "fighters who turned pro in 2015", (b) => b.turnedPro === 2015),
    c("B", "combined: division + losing record", "heavyweights with a losing record", (b) => b.weightClass === "Heavyweight" && b.losses > b.wins),
    c("B", "combined: division + losses", "welterweights with more than 10 losses", (b) => b.weightClass === "Welterweight" && b.losses > 10),
    c("B", "combined: stance + wins + no losses", "southpaws with at least 15 wins and no losses", (b) => b.stance === "Southpaw" && b.wins >= 15 && b.losses === 0),
    c("B", "combined: sex + fights", "women with fewer than 5 fights", (b) => b.sex === "female" && b.bouts < 5),
    c("B", "combined: active + age + wins", "active fighters over 30 with more than 20 wins", (b) => b.active && known(b.age, (a) => a >= 31) && b.wins > 20),
    c("B", "combined: knockouts + no losses", "fighters with 10 or more knockouts and no losses", (b) => b.kos >= 10 && b.losses === 0),
    c("B", "combined: wins range + division", "heavyweights between 20 and 30 wins", (b) => b.weightClass === "Heavyweight" && b.wins >= 20 && b.wins <= 30),
    // D: the same kinds of sentence in Arabic (round 52), written before the Arabic parser was and measured on the parser as it was
    c("D", "ar losses, more than", "ملاكمون لديهم أكثر من 10 هزائم", (b) => b.losses > 10),
    c("D", "ar losses, more than, Arabic-Indic digits", "ملاكمون لديهم أكثر من ١٠ هزائم", (b) => b.losses > 10),
    c("D", "ar losses, none", "ملاكمون بدون هزائم", (b) => b.losses === 0),
    c("D", "ar losses, never", "ملاكمون لم يخسروا أبدا", (b) => b.losses === 0),
    c("D", "ar losses, exactly", "ملاكمون لديهم 4 هزائم بالضبط", (b) => b.losses === 4),
    c("D", "ar losses, at most", "ملاكمون لديهم 3 هزائم على الأكثر", (b) => b.losses <= 3),
    c("D", "ar losses, fewer than", "ملاكمون لديهم أقل من 3 هزائم", (b) => b.losses < 3),
    c("D", "ar losses, at least", "ملاكمون لديهم 8 هزائم على الأقل", (b) => b.losses >= 8),
    c("D", "ar wins, more than", "ملاكمون لديهم أكثر من 25 فوزا", (b) => b.wins > 25),
    c("D", "ar wins, at least", "ملاكمون لديهم 20 فوزا على الأقل", (b) => b.wins >= 20),
    c("D", "ar wins, fewer than", "ملاكمون لديهم أقل من 10 انتصارات", (b) => b.wins < 10),
    c("D", "ar wins, between", "ملاكمون لديهم بين 15 و25 فوزا", (b) => b.wins >= 15 && b.wins <= 25),
    c("D", "ar wins, from to", "ملاكمون لديهم من 20 إلى 30 فوزا", (b) => b.wins >= 20 && b.wins <= 30),
    c("D", "ar wins, none", "ملاكمون لم يفوزوا أبدا", (b) => b.wins === 0),
    c("D", "ar wins, number word", "ملاكمون لديهم أكثر من عشرين فوزا", (b) => b.wins > 20),
    c("D", "ar knockouts, or more", "ملاكمون لديهم 10 ضربات قاضية أو أكثر", (b) => b.kos >= 10),
    c("D", "ar knockouts, more than", "ملاكمون لديهم أكثر من 10 ضربات قاضية", (b) => b.kos > 10),
    c("D", "ar knockouts, none", "ملاكمون بدون ضربات قاضية", (b) => b.kos === 0),
    c("D", "ar fights, fewer than", "ملاكمون لديهم أقل من 10 نزالات", (b) => b.bouts < 10),
    c("D", "ar fights, more than", "ملاكمون لديهم أكثر من 30 نزالا", (b) => b.bouts > 30),
    c("D", "ar fights, at least", "ملاكمون خاضوا 25 نزالا على الأقل", (b) => b.bouts >= 25),
    c("D", "ar age, over", "ملاكمون أعمارهم فوق 35", (b) => known(b.age, (a) => a >= 36)),
    c("D", "ar age, under", "ملاكمون تحت 25 سنة", (b) => known(b.age, (a) => a < 25)),
    c("D", "ar age, between", "ملاكمون بين 25 و30 سنة", (b) => known(b.age, (a) => a >= 25 && a <= 30)),
    c("D", "ar age, older than", "ملاكمون أكبر من 38 سنة", (b) => known(b.age, (a) => a > 38)),
    c("D", "ar height, taller", "ملاكمون أطول من 185 سم", (b) => known(b.heightCm, (h) => h > 185)),
    c("D", "ar height, shorter", "ملاكمون أقصر من 170 سم", (b) => known(b.heightCm, (h) => h < 170)),
    c("D", "ar reach, more than", "ملاكمون امتداد ذراعيهم أكثر من 190", (b) => known(b.reachCm, (r) => r > 190)),
    c("D", "ar reach, at least", "ملاكمون امتداد ذراعيهم 190 سم على الأقل", (b) => known(b.reachCm, (r) => r >= 190)),
    c("D", "ar record, losing", "ملاكمون سجلهم خاسر", (b) => b.losses > b.wins),
    c("D", "ar record, winning", "ملاكمون سجلهم رابح", (b) => b.wins > b.losses),
    c("D", "ar combined: division + wins", "ملاكمو الوزن المتوسط لديهم أكثر من 15 فوزا", (b) => b.weightClass === "Middleweight" && b.wins > 15),
    c("D", "ar combined: heavyweights + losing", "ثقيلو الوزن بسجل خاسر", (b) => b.weightClass === "Heavyweight" && b.losses > b.wins),
    c("D", "ar combined: wins + no losses", "ملاكمون لديهم 15 فوزا على الأقل وبدون هزائم", (b) => b.wins >= 15 && b.losses === 0),
    c("D", "ar combined: two measures", "ملاكمون لديهم أكثر من 15 فوزا وأقل من 4 هزائم", (b) => b.wins > 15 && b.losses < 4),
    c("D", "ar combined: women + fights", "ملاكمات لديهن أقل من 5 نزالات", (b) => b.sex === "female" && b.bouts < 5),
    c("D", "ar combined: country + losses", "ملاكمون من المكسيك لديهم أكثر من 8 هزائم", (b) => b.country === "Mexico" && b.losses > 8),
    c("D", "ar combined: southpaw + wins", "ملاكمون أعسر لديهم أكثر من 20 فوزا", (b) => b.stance === "Southpaw" && b.wins > 20),
    // E: a second Arabic batch, other wordings, written after the Arabic parser was fitted and measured once before anything was changed for it
    c("E", "ar losses, without hamza", "ملاكمون لديهم اكثر من 12 خسارة", (b) => b.losses > 12),
    c("E", "ar losses, لا يزيد", "ملاكمون لا يزيد عدد هزائمهم عن 5", (b) => b.losses <= 5),
    c("E", "ar losses, لا يقل عن", "ملاكمون لديهم لا يقل عن 6 خسائر", (b) => b.losses >= 6),
    c("E", "ar losses, ليس لديهم", "ملاكمون ليس لديهم هزائم", (b) => b.losses === 0),
    c("E", "ar losses, number word, at most", "ملاكمون لديهم ثلاث هزائم على الأكثر", (b) => b.losses <= 3),
    c("E", "ar losses, number word, more than", "ملاكمون لديهم أكثر من خمس هزائم", (b) => b.losses > 5),
    c("E", "ar wins, فأكثر", "ملاكمون لديهم 25 فوزا فأكثر", (b) => b.wins >= 25),
    c("E", "ar wins, فاقل", "ملاكمون لديهم 8 انتصارات فأقل", (b) => b.wins <= 8),
    c("E", "ar wins, بلا", "ملاكمون بلا انتصارات", (b) => b.wins === 0),
    c("E", "ar wins, لا يقل عن", "ملاكمون لا يقل عدد انتصاراتهم عن 30", (b) => b.wins >= 30),
    c("E", "ar knockouts, بلا", "ملاكمون بلا ضربات قاضية", (b) => b.kos === 0),
    c("E", "ar knockouts, at least", "ملاكمون لديهم 12 ضربة قاضية على الأقل", (b) => b.kos >= 12),
    c("E", "ar knockouts, between", "ملاكمون لديهم بين 5 و10 ضربات قاضية", (b) => b.kos >= 5 && b.kos <= 10),
    c("E", "ar fights, less than", "ملاكمون خاضوا أقل من 8 نزالات", (b) => b.bouts < 8),
    c("E", "ar fights, between", "ملاكمون خاضوا بين 10 و20 نزالا", (b) => b.bouts >= 10 && b.bouts <= 20),
    c("E", "ar age, دون", "ملاكمون دون 25 عاما", (b) => known(b.age, (a) => a < 25)),
    c("E", "ar age, من إلى", "ملاكمون من 30 إلى 35 سنة", (b) => known(b.age, (a) => a >= 30 && a <= 35)),
    c("E", "ar age, exactly", "ملاكمون عمرهم 30 سنة", (b) => b.age === 30),
    c("E", "ar age, عمرهم", "ملاكمون عمرهم أكثر من 38 سنة", (b) => known(b.age, (a) => a > 38)),
    c("E", "ar age, يزيد عمرهم", "ملاكمون يزيد عمرهم عن 35 سنة", (b) => known(b.age, (a) => a > 35)),
    c("E", "ar age, or more", "ملاكمون 36 سنة فأكثر", (b) => known(b.age, (a) => a >= 36)),
    c("E", "ar height, بين", "ملاكمون طولهم بين 175 و185 سم", (b) => known(b.heightCm, (h) => h >= 175 && h <= 185)),
    c("E", "ar height, طولهم", "ملاكمون طولهم أكثر من 180 سم", (b) => known(b.heightCm, (h) => h > 180)),
    c("E", "ar height, at least", "ملاكمون لا يقل طولهم عن 190 سم", (b) => known(b.heightCm, (h) => h >= 190)),
    c("E", "ar reach, طول الذراعين", "ملاكمون طول ذراعيهم أقل من 175", (b) => known(b.reachCm, (r) => r < 175)),
    c("E", "ar reach, بين", "ملاكمون امتداد ذراعيهم بين 180 و190", (b) => known(b.reachCm, (r) => r >= 180 && r <= 190)),
    c("E", "ar record, سجل سلبي", "ملاكمون بسجل سلبي", (b) => b.losses > b.wins),
    c("E", "ar record, سجل إيجابي", "ملاكمون بسجل إيجابي", (b) => b.wins > b.losses),
    c("E", "ar combined: division + age", "ملاكمو الوزن الثقيل أكبر من 30 سنة", (b) => b.weightClass === "Heavyweight" && known(b.age, (a) => a > 30)),
    c("E", "ar combined: women + wins", "ملاكمات لديهن أكثر من 5 انتصارات", (b) => b.sex === "female" && b.wins > 5),
    c("E", "ar combined: active + wins", "ملاكمون نشطون لديهم أكثر من 25 فوزا", (b) => b.active && b.wins > 25),
    c("E", "ar combined: retired + losses", "ملاكمون معتزلون لديهم أكثر من 15 هزيمة", (b) => !b.active && b.losses > 15),
    c("E", "ar combined: Indic digits range", "ملاكمون لديهم بين ١٥ و٢٥ فوزا", (b) => b.wins >= 15 && b.wins <= 25),
    c("E", "ar combined: stance + losses", "ملاكمون أعسر ليس لديهم هزائم", (b) => b.stance === "Southpaw" && b.losses === 0),
    c("E", "ar combined: KOs + no losses", "ملاكمون لديهم 8 ضربات قاضية أو أكثر وبدون هزائم", (b) => b.kos >= 8 && b.losses === 0),
    // F: a fighter's record and form: stopped, draws, streaks, unbeaten runs, when they last fought (round 53); measured on the search as it was
    c("F", "stopped, never", "fighters who have never been knocked out", (b) => b.koLosses === 0),
    c("F", "stopped, never (stopped)", "boxers who have never been stopped", (b) => b.koLosses === 0),
    c("F", "stopped, never lost by knockout", "boxers who never lost by knockout", (b) => b.koLosses === 0),
    c("F", "stopped, more than twice", "fighters stopped more than twice", (b) => b.koLosses > 2),
    c("F", "stopped, at least 3 times", "boxers who lost by knockout at least 3 times", (b) => b.koLosses >= 3),
    c("F", "stopped, been knocked out more than once", "boxers who have been knocked out more than once", (b) => b.koLosses > 1),
    c("F", "stopped, KO losses", "fighters with 5 or more KO losses", (b) => b.koLosses >= 5),
    c("F", "stopped, fewer than", "fighters stopped fewer than 2 times", (b) => b.koLosses < 2),
    c("F", "stopped, active voice is wins by knockout", "fighters who have knocked out at least 10 opponents", (b) => b.kos >= 10),
    c("F", "distance, every time", "fighters who went the distance every time", (b) => b.koLosses === 0 && b.kos === 0),
    c("F", "draws, with a draw", "fighters with a draw", (b) => b.draws >= 1),
    c("F", "draws, none", "fighters with no draws", (b) => b.draws === 0),
    c("F", "draws, more than", "fighters with more than 2 draws", (b) => b.draws > 2),
    c("F", "draws, never drawn", "fighters who have never drawn", (b) => b.draws === 0),
    c("F", "draws, exactly", "fighters with exactly 2 draws", (b) => b.draws === 2),
    c("F", "streak, winning of at least", "fighters on a winning streak of at least 5", (b) => b.streak.type === "W" && b.streak.count >= 5),
    c("F", "streak, N fight winning", "fighters on a 4 fight winning streak", (b) => b.streak.type === "W" && b.streak.count >= 4),
    c("F", "streak, won their last", "fighters who have won their last 3", (b) => b.streak.type === "W" && b.streak.count >= 3),
    c("F", "streak, bare winning", "fighters on a winning streak", (b) => b.streak.type === "W" && b.streak.count >= 2),
    c("F", "streak, losing", "fighters on a losing streak", (b) => b.streak.type === "L" && b.streak.count >= 2),
    c("F", "streak, lost their last two", "boxers who lost their last two", (b) => b.streak.type === "L" && b.streak.count >= 2),
    c("F", "streak, lost last fight", "fighters who lost their last fight", (b) => b.streak.type === "L"),
    c("F", "streak, won last fight", "boxers who won their last fight", (b) => b.streak.type === "W"),
    c("F", "streak, losing of at least 3", "fighters on a losing streak of at least 3", (b) => b.streak.type === "L" && b.streak.count >= 3),
    c("F", "unbeaten in last 5", "fighters unbeaten in their last 5", (b, w) => { const l = record(b, w); return l.length >= 5 && l.slice(-5).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("F", "undefeated in last 3 fights", "boxers undefeated in their last 3 fights", (b, w) => { const l = record(b, w); return l.length >= 3 && l.slice(-3).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("F", "recent, last 6 months", "fighters who fought in the last 6 months", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 6, "months")),
    c("F", "recent, past year", "boxers who have fought in the past year", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    c("F", "recent, this year", "fighters who fought this year", (b, w) => b.lastFight !== null && b.lastFight >= w.today.slice(0, 4) + "-01-01"),
    c("F", "inactive, over a year", "fighters who have not fought in over a year", (b, w) => b.lastFight !== null && b.lastFight < back(w, 1, "years")),
    c("F", "inactive, for 2 years", "fighters inactive for 2 years", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 2, "years")),
    c("F", "last fought in a year", "fighters who last fought in 2024", (b) => b.lastFight !== null && b.lastFight.startsWith("2024")),
    c("F", "last fought, haven't since", "boxers who haven't fought since 2023", (b) => b.lastFight !== null && b.lastFight <= "2023-12-31"),
    c("F", "ko rate, under", "fighters with a ko rate under 30%", (b) => b.wins > 0 && b.koRate <= 0.3),
    c("F", "combined: division + never stopped", "heavyweights who have never been stopped", (b) => b.weightClass === "Heavyweight" && b.koLosses === 0),
    c("F", "combined: streak + age", "boxers over 35 on a winning streak", (b) => known(b.age, (a) => a >= 36) && b.streak.type === "W" && b.streak.count >= 2),
    c("F", "combined: recent + wins", "fighters with more than 20 wins who fought in the last year", (b, w) => b.wins > 20 && b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    c("F", "combined: no draws + never stopped", "fighters with no draws who have never been knocked out", (b) => b.draws === 0 && b.koLosses === 0),
    // G: a second batch on record and form, other wordings, written after the first was fitted and measured once before anything was changed for it
    c("G", "stopped, KO'd", "boxers who have never been KO'd", (b) => b.koLosses === 0),
    c("G", "stopped, were never", "fighters who were never knocked out", (b) => b.koLosses === 0),
    c("G", "stopped, twice", "fighters knocked out twice", (b) => b.koLosses >= 2),
    c("G", "stopped, exactly once", "fighters stopped exactly once", (b) => b.koLosses === 1),
    c("G", "stopped, no KO losses", "boxers with no knockout losses", (b) => b.koLosses === 0),
    c("G", "stopped, at most 1 KO loss", "fighters with at most 1 KO loss", (b) => b.koLosses <= 1),
    c("G", "stopped, at least 4 times", "fighters who have been stopped at least 4 times", (b) => b.koLosses >= 4),
    c("G", "stopped, by stoppage", "boxers who lost by stoppage more than 3 times", (b) => b.koLosses > 3),
    c("G", "draws, drawn at least once", "boxers who have drawn at least once", (b) => b.draws >= 1),
    c("G", "draws, 3 or more", "fighters with 3 or more draws", (b) => b.draws >= 3),
    c("G", "draws, fewer than", "fighters with fewer than 2 draws", (b) => b.draws < 2),
    c("G", "draws, never fought a draw", "fighters who never fought a draw", (b) => b.draws === 0),
    c("G", "streak, 6 fight", "fighters on a 6 fight winning streak", (b) => b.streak.type === "W" && b.streak.count >= 6),
    c("G", "streak, won their last 5 fights", "boxers who have won their last 5 fights", (b) => b.streak.type === "W" && b.streak.count >= 5),
    c("G", "streak, lost their last 3 fights", "fighters who lost their last 3 fights", (b) => b.streak.type === "L" && b.streak.count >= 3),
    c("G", "streak, word number", "fighters on a three fight losing streak", (b) => b.streak.type === "L" && b.streak.count >= 3),
    c("G", "streak, riding", "fighters riding a winning streak", (b) => b.streak.type === "W" && b.streak.count >= 2),
    c("G", "streak, of 4", "fighters with a winning streak of 4", (b) => b.streak.type === "W" && b.streak.count >= 4),
    c("G", "unbeaten, haven't lost", "fighters who haven't lost in their last 4", (b, w) => { const l = record(b, w); return l.length >= 4 && l.slice(-4).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("G", "unbeaten, no losses in", "fighters with no losses in their last 5 fights", (b, w) => { const l = record(b, w); return l.length >= 5 && l.slice(-5).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("G", "unbeaten, over their last", "boxers unbeaten over their last 6 fights", (b, w) => { const l = record(b, w); return l.length >= 6 && l.slice(-6).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("G", "recent, within 3 months", "fighters who fought within the last 3 months", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 3, "months")),
    c("G", "recent, last 2 years", "fighters who have fought in the last 2 years", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 2, "years")),
    c("G", "recent, last year", "fighters who fought last year", (b, w) => { const y = +w.today.slice(0, 4) - 1; return b.lastFight !== null && b.lastFight >= `${y}-01-01` && b.lastFight <= `${y}-12-31`; }),
    c("G", "recent, since", "fighters who have fought since 2025", (b) => b.lastFight !== null && b.lastFight >= "2025-01-01"),
    c("G", "inactive, at least 18 months", "fighters who haven't fought in at least 18 months", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 18, "months")),
    c("G", "inactive, more than 2 years", "boxers who haven't been in a fight for more than 2 years", (b, w) => b.lastFight !== null && b.lastFight < back(w, 2, "years")),
    c("G", "inactive, over a year", "boxers who have been inactive for over a year", (b, w) => b.lastFight !== null && b.lastFight < back(w, 1, "years")),
    c("G", "last fought before", "fighters who last fought before 2023", (b) => b.lastFight !== null && b.lastFight < "2023-01-01"),
    c("G", "ko rate, below", "boxers with a knockout rate below 20%", (b) => b.wins > 0 && b.koRate <= 0.2),
    c("G", "ko rate, at most", "fighters with a ko rate of at most 25%", (b) => b.wins > 0 && b.koRate <= 0.25),
    c("G", "combined: women + never stopped", "women who have never been knocked out", (b) => b.sex === "female" && b.koLosses === 0),
    c("G", "combined: undefeated + streak", "undefeated fighters on a winning streak of at least 5", (b) => b.losses === 0 && b.streak.type === "W" && b.streak.count >= 5),
    c("G", "combined: country + recent", "Mexican fighters who fought in the last year", (b, w) => b.country === "Mexico" && b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    c("G", "combined: stopped + wins", "fighters with more than 20 wins who have never been stopped", (b) => b.wins > 20 && b.koLosses === 0),
    c("G", "combined: losing streak + age", "fighters under 30 on a losing streak", (b) => known(b.age, (a) => a < 30) && b.streak.type === "L" && b.streak.count >= 2),
    // H: a fighter's record and form in Arabic (round 54), written before the Arabic parser read them and measured on the parser as it was
    c("H", "ar stopped, never", "ملاكمون لم يتعرضوا للضربة القاضية أبدا", (b) => b.koLosses === 0),
    c("H", "ar stopped, never lost by KO", "ملاكمون لم يخسروا بالضربة القاضية أبدا", (b) => b.koLosses === 0),
    c("H", "ar stopped, at least", "ملاكمون خسروا بالضربة القاضية 3 مرات على الأقل", (b) => b.koLosses >= 3),
    c("H", "ar stopped, more than twice", "ملاكمون تعرضوا للضربة القاضية أكثر من مرتين", (b) => b.koLosses > 2),
    c("H", "ar stopped, KO losses", "ملاكمون لديهم 5 هزائم بالضربة القاضية على الأقل", (b) => b.koLosses >= 5),
    c("H", "ar draws, with", "ملاكمون لديهم تعادل", (b) => b.draws >= 1),
    c("H", "ar draws, none", "ملاكمون بدون تعادلات", (b) => b.draws === 0),
    c("H", "ar draws, never", "ملاكمون لم يتعادلوا أبدا", (b) => b.draws === 0),
    c("H", "ar draws, more than two", "ملاكمون لديهم أكثر من تعادلين", (b) => b.draws > 2),
    c("H", "ar draws, more than", "ملاكمون لديهم أكثر من 2 تعادلات", (b) => b.draws > 2),
    c("H", "ar streak, winning of 5", "ملاكمون في سلسلة انتصارات من 5 نزالات", (b) => b.streak.type === "W" && b.streak.count >= 5),
    c("H", "ar streak, won their last 3", "ملاكمون فازوا في آخر 3 نزالات", (b) => b.streak.type === "W" && b.streak.count >= 3),
    c("H", "ar streak, lost their last fight", "ملاكمون خسروا نزالهم الأخير", (b) => b.streak.type === "L"),
    c("H", "ar streak, won their last fight", "ملاكمون فازوا بنزالهم الأخير", (b) => b.streak.type === "W"),
    c("H", "ar streak, losing", "ملاكمون في سلسلة هزائم", (b) => b.streak.type === "L" && b.streak.count >= 2),
    c("H", "ar streak, lost their last two", "ملاكمون خسروا آخر نزالين", (b) => b.streak.type === "L" && b.streak.count >= 2),
    c("H", "ar streak, winning, bare", "ملاكمون في سلسلة انتصارات", (b) => b.streak.type === "W" && b.streak.count >= 2),
    c("H", "ar unbeaten in last 5", "ملاكمون لم يخسروا في آخر 5 نزالات", (b, w) => { const l = record(b, w); return l.length >= 5 && l.slice(-5).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("H", "ar unbeaten, ثلاثة", "ملاكمون غير مهزومين في آخر 3 نزالات", (b, w) => { const l = record(b, w); return l.length >= 3 && l.slice(-3).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("H", "ar recent, last 6 months", "ملاكمون خاضوا نزالا في آخر 6 أشهر", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 6, "months")),
    c("H", "ar recent, last year", "ملاكمون خاضوا نزالا في آخر سنة", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    c("H", "ar recent, this year", "ملاكمون خاضوا نزالا هذا العام", (b, w) => b.lastFight !== null && b.lastFight >= w.today.slice(0, 4) + "-01-01"),
    c("H", "ar inactive, over a year", "ملاكمون لم يخوضوا نزالا منذ أكثر من سنة", (b, w) => b.lastFight !== null && b.lastFight < back(w, 1, "years")),
    c("H", "ar inactive, since two years", "ملاكمون لا نشاط لهم منذ سنتين", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 2, "years")),
    c("H", "ar last fought in a year", "ملاكمون خاضوا آخر نزال لهم في 2024", (b) => b.lastFight !== null && b.lastFight.startsWith("2024")),
    c("H", "ar last fought before", "ملاكمون آخر نزال لهم قبل 2023", (b) => b.lastFight !== null && b.lastFight < "2023-01-01"),
    c("H", "ar debut, in", "ملاكمون احترفوا في 2015", (b) => b.turnedPro === 2015),
    c("H", "ar debut, after", "ملاكمون بدأوا الاحتراف بعد 2018", (b) => b.turnedPro !== null && b.turnedPro > 2018),
    c("H", "ar debut, before", "ملاكمون احترفوا قبل 2013", (b) => b.turnedPro !== null && b.turnedPro < 2013),
    c("H", "ar ko rate, under", "ملاكمون نسبة ضرباتهم القاضية أقل من 30%", (b) => b.wins > 0 && b.koRate <= 0.3),
    c("H", "ar ko rate, over", "ملاكمون نسبة ضرباتهم القاضية أكثر من 70%", (b) => b.koRate >= 0.7),
    c("H", "ar combined: heavyweights + never stopped", "ثقيلو الوزن لم يتعرضوا للضربة القاضية أبدا", (b) => b.weightClass === "Heavyweight" && b.koLosses === 0),
    c("H", "ar combined: women + streak", "ملاكمات في سلسلة انتصارات", (b) => b.sex === "female" && b.streak.type === "W" && b.streak.count >= 2),
    c("H", "ar combined: wins + recent", "ملاكمون لديهم أكثر من 20 فوزا خاضوا نزالا في آخر سنة", (b, w) => b.wins > 20 && b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    c("H", "ar combined: no draws + never stopped", "ملاكمون بدون تعادلات لم يتعرضوا للضربة القاضية أبدا", (b) => b.draws === 0 && b.koLosses === 0),
    // I: a second Arabic batch on record and form, other wordings, written after the first was fitted and measured once before anything was changed for it
    c("I", "ar stopped, لم يخسر", "ملاكمون لم يخسر أي منهم بالضربة القاضية", (b) => b.koLosses === 0),
    c("I", "ar stopped, بدون هزائم بالضربة", "ملاكمون بدون هزائم بالضربة القاضية", (b) => b.koLosses === 0),
    c("I", "ar stopped, تعرضوا مرتين", "ملاكمون تعرضوا للضربة القاضية مرتين على الأقل", (b) => b.koLosses >= 2),
    c("I", "ar stopped, 4 مرات", "ملاكمون خسروا بالضربة القاضية أكثر من 4 مرات", (b) => b.koLosses > 4),
    c("I", "ar stopped, ثلاث هزائم", "ملاكمون لديهم ثلاث هزائم بالضربة القاضية", (b) => b.koLosses >= 3),
    c("I", "ar draws, ليس لديهم", "ملاكمون ليس لديهم تعادلات", (b) => b.draws === 0),
    c("I", "ar draws, تعادلين على الأقل", "ملاكمون لديهم تعادلين على الأقل", (b) => b.draws >= 2),
    c("I", "ar draws, less than", "ملاكمون لديهم أقل من 3 تعادلات", (b) => b.draws < 3),
    c("I", "ar draws, بلا", "ملاكمون بلا تعادلات", (b) => b.draws === 0),
    c("I", "ar streak, 4 انتصارات", "ملاكمون في سلسلة انتصارات من 4 نزالات على الأقل", (b) => b.streak.type === "W" && b.streak.count >= 4),
    c("I", "ar streak, سلسلة هزائم من 3", "ملاكمون في سلسلة هزائم من 3 نزالات", (b) => b.streak.type === "L" && b.streak.count >= 3),
    c("I", "ar streak, انتصروا في آخر 4", "ملاكمون انتصروا في آخر 4 نزالات", (b) => b.streak.type === "W" && b.streak.count >= 4),
    c("I", "ar streak, number word", "ملاكمون فازوا في آخر ثلاثة نزالات", (b) => b.streak.type === "W" && b.streak.count >= 3),
    c("I", "ar streak, خسروا آخر 3", "ملاكمون خسروا آخر 3 نزالات", (b) => b.streak.type === "L" && b.streak.count >= 3),
    c("I", "ar streak, women lost last", "ملاكمات خسرن نزالهن الأخير", (b) => b.sex === "female" && b.streak.type === "L"),
    c("I", "ar unbeaten, 4", "ملاكمون لم يخسروا في آخر 4 نزالات", (b, w) => { const l = record(b, w); return l.length >= 4 && l.slice(-4).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("I", "ar unbeaten, بدون هزائم في", "ملاكمون بدون هزائم في آخر 6 نزالات", (b, w) => { const l = record(b, w); return l.length >= 6 && l.slice(-6).every((x) => x.winnerId === null || x.winnerId === b.id); }),
    c("I", "ar recent, 3 months", "ملاكمون خاضوا نزالا في آخر 3 أشهر", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 3, "months")),
    c("I", "ar recent, 2 years", "ملاكمون خاضوا نزالا في آخر سنتين", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 2, "years")),
    c("I", "ar recent, number word", "ملاكمون خاضوا نزالا في آخر ثلاثة أشهر", (b, w) => b.lastFight !== null && b.lastFight >= back(w, 3, "months")),
    c("I", "ar recent, last year", "ملاكمون خاضوا نزالا العام الماضي", (b, w) => { const y = +w.today.slice(0, 4) - 1; return b.lastFight !== null && b.lastFight >= `${y}-01-01` && b.lastFight <= `${y}-12-31`; }),
    c("I", "ar inactive, 18 months", "ملاكمون لم يخوضوا نزالا منذ 18 شهرا على الأقل", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 18, "months")),
    c("I", "ar inactive, since a year", "ملاكمون لا نشاط لهم منذ أكثر من سنة", (b, w) => b.lastFight !== null && b.lastFight < back(w, 1, "years")),
    c("I", "ar inactive, since 2023", "ملاكمون لم يخوضوا نزالا منذ 2023", (b) => b.lastFight !== null && b.lastFight <= "2023-12-31"),
    c("I", "ar last fought since", "ملاكمون آخر نزال لهم منذ 2025", (b) => b.lastFight !== null && b.lastFight >= "2025-01-01"),
    c("I", "ar debut, بدأوا مسيرتهم", "ملاكمون بدأوا مسيرتهم الاحترافية في 2018", (b) => b.turnedPro === 2018),
    c("I", "ar debut, منذ", "ملاكمون احترفوا منذ 2020", (b) => b.turnedPro !== null && b.turnedPro >= 2020),
    c("I", "ar ko rate, تحت", "ملاكمون نسبة ضرباتهم القاضية تحت 20%", (b) => b.wins > 0 && b.koRate <= 0.2),
    c("I", "ar ko rate, at least", "ملاكمون نسبة الضربات القاضية لديهم على الأقل 60%", (b) => b.koRate >= 0.6),
    c("I", "ar combined: country + streak", "ملاكمون من المكسيك في سلسلة هزائم", (b) => b.country === "Mexico" && b.streak.type === "L" && b.streak.count >= 2),
    c("I", "ar combined: age + never stopped", "ملاكمون فوق 35 سنة لم يتعرضوا للضربة القاضية أبدا", (b) => known(b.age, (a) => a >= 36) && b.koLosses === 0),
    c("I", "ar combined: undefeated + streak", "ملاكمون بدون هزائم في سلسلة انتصارات من 5 نزالات", (b) => b.losses === 0 && b.streak.type === "W" && b.streak.count >= 5),
    c("I", "ar combined: southpaw + recent", "ملاكمون أعسر خاضوا نزالا في آخر سنة", (b, w) => b.stance === "Southpaw" && b.lastFight !== null && b.lastFight >= back(w, 1, "years")),
    // J: records as they are written, a draw fought, a year of not fighting, a rating range (round 67); measured on the search as it was
    c("J", "record 2-4", "fighters who are 2-4", (b) => b.wins === 2 && b.losses === 4),
    c("J", "record 3-5", "boxers with a 3-5 record", (b) => b.wins === 3 && b.losses === 5),
    c("J", "record with draws", "fighters who are 2-6-0", (b) => b.wins === 2 && b.losses === 6 && b.draws === 0),
    c("J", "record, division", "welterweights who are 2-4", (b) => b.weightClass === "Welterweight" && b.wins === 2 && b.losses === 4),
    c("J", "record, 1 loss", "fighters who are 1-4", (b) => b.wins === 1 && b.losses === 4),
    c("J", "record, 1 loss", "women who are 9-1", (b) => b.sex === "female" && b.wins === 9 && b.losses === 1),
    c("J", "draw fought", "fighters who have fought a draw", (b) => b.draws >= 1),
    c("J", "draw fought + never stopped", "fighters who have fought a draw and never been stopped", (b) => b.draws >= 1 && b.koLosses === 0),
    c("J", "draw, fought to", "boxers who fought to a draw", (b) => b.draws >= 1),
    c("J", "a year without a fight", "fighters who haven't fought in a year", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 1, "years")),
    c("J", "two years without", "boxers who haven't fought in 2 years", (b, w) => b.lastFight !== null && b.lastFight <= back(w, 2, "years")),
    c("J", "active + a year without", "active fighters who haven't fought in a year", (b, w) => b.active && b.lastFight !== null && b.lastFight <= back(w, 1, "years")),
    c("J", "rating range hyphen", "fighters rated 1500-1600", (b) => Math.round(b.rating) >= 1500 && Math.round(b.rating) <= 1600),
    c("J", "rating between", "fighters rated between 1550 and 1650", (b) => Math.round(b.rating) >= 1550 && Math.round(b.rating) <= 1650),
    c("J", "rating over", "boxers with a rating over 1600", (b) => Math.round(b.rating) > 1600),
    c("J", "wins hyphen range stays a range", "fighters with 5-10 wins", (b) => b.wins >= 5 && b.wins <= 10),
    // C: a second batch, other wordings, written after the parser and measured once before anything was changed for it
    c("C", "losses, lost N times", "fighters who have lost more than 5 times", (b) => b.losses > 5),
    c("C", "wins, won N times", "fighters who have won at least 20 times", (b) => b.wins >= 20),
    c("C", "fights, fought N times", "fighters who have fought exactly 15 times", (b) => b.bouts === 15),
    c("C", "losses, fewer than, plural", "welterweights with fewer than 2 defeats", (b) => b.weightClass === "Welterweight" && b.losses < 2),
    c("C", "wins, 30 or more", "boxers who have 30 or more victories", (b) => b.wins >= 30),
    c("C", "wins, no more than", "boxers with no more than 5 wins", (b) => b.wins <= 5),
    c("C", "wins, up to", "boxers with up to 8 wins", (b) => b.wins <= 8),
    c("C", "wins, plus", "boxers with 30 plus wins", (b) => b.wins >= 30),
    c("C", "kos, a minimum of", "fighters with a minimum of 12 knockouts", (b) => b.kos >= 12),
    c("C", "kos, zero", "fighters with zero knockouts", (b) => b.kos === 0),
    c("C", "kos, 20+", "fighters with 20+ KOs", (b) => b.kos >= 20),
    c("C", "bouts, greater than", "boxers with greater than 40 bouts", (b) => b.bouts > 40),
    c("C", "bouts, less than", "boxers with less than 6 bouts", (b) => b.bouts < 6),
    c("C", "bouts, professional", "boxers with at least 20 professional fights", (b) => b.bouts >= 20),
    c("C", "age, 40 and over", "boxers 40 and over", (b) => known(b.age, (a) => a >= 40)),
    c("C", "age, older than", "boxers older than 38", (b) => known(b.age, (a) => a > 38)),
    c("C", "age, years old, exact", "boxers 30 years old", (b) => b.age === 30),
    c("C", "age, aged exact", "boxers aged 27", (b) => b.age === 27),
    c("C", "age, ages range", "fighters ages 22 to 26", (b) => known(b.age, (a) => a >= 22 && a <= 26)),
    c("C", "age, 25 or younger", "fighters 25 or younger", (b) => known(b.age, (a) => a <= 25)),
    c("C", "age, under + division", "heavyweights under 30", (b) => b.weightClass === "Heavyweight" && known(b.age, (a) => a < 30)),
    c("C", "reach, 200", "boxers with a reach of 200 or more", (b) => known(b.reachCm, (r) => r >= 200)),
    c("C", "reach, 180 cm", "boxers with 180 cm reach or less", (b) => known(b.reachCm, (r) => r <= 180)),
    c("C", "reach, between", "boxers with a reach between 180 and 190", (b) => known(b.reachCm, (r) => r >= 180 && r <= 190)),
    c("C", "height, cm tall", "fighters 180 cm tall or more", (b) => known(b.heightCm, (h) => h >= 180)),
    c("C", "height, 6ft 2", "fighters taller than 6 ft 2", (b) => known(b.heightCm, (h) => h > 187.96)),
    c("C", "height, under 5 ft 8", "fighters under 5'8", (b) => known(b.heightCm, (h) => h < 172.72)),
    c("C", "height, between", "fighters between 175 and 185 cm", (b) => known(b.heightCm, (h) => h >= 175 && h <= 185)),
    c("C", "record, winning + country", "Mexican boxers with a winning record", (b) => b.country === "Mexico" && b.wins > b.losses),
    c("C", "record, losing + age", "boxers over 35 with a losing record", (b) => known(b.age, (a) => a >= 36) && b.losses > b.wins),
    c("C", "record, more wins than losses", "fighters with more wins than losses", (b) => b.wins > b.losses),
    c("C", "winless", "winless fighters", (b) => b.wins === 0),
    c("C", "never won", "fighters who have never won", (b) => b.wins === 0),
    c("C", "turned pro before", "fighters who turned pro before 2012", (b) => b.turnedPro !== null && b.turnedPro < 2012),
    c("C", "turned pro after", "fighters who turned pro after 2020", (b) => b.turnedPro !== null && b.turnedPro > 2020),
    c("C", "turned pro since", "fighters who turned pro since 2020", (b) => b.turnedPro !== null && b.turnedPro >= 2020),
    c("C", "combined: two measures", "fighters with more than 15 wins and fewer than 4 losses", (b) => b.wins > 15 && b.losses < 4),
    c("C", "combined: wins + knockouts", "boxers with at least 20 wins and at least 15 knockouts", (b) => b.wins >= 20 && b.kos >= 15),
    c("C", "combined: losses + age + division", "middleweights over 30 with 5 or more losses", (b) => b.weightClass === "Middleweight" && known(b.age, (a) => a >= 31) && b.losses >= 5),
    c("C", "combined: country + fights", "Japanese fighters with fewer than 8 fights", (b) => b.country === "Japan" && b.bouts < 8),
    c("C", "combined: no losses + height", "undefeated fighters taller than 180 cm", (b) => b.losses === 0 && known(b.heightCm, (h) => h > 180)),
    c("C", "combined: retired + wins", "retired fighters with more than 25 wins", (b) => !b.active && b.wins > 25),
    c("C", "combined: women + wins range", "women with between 5 and 10 wins", (b) => b.sex === "female" && b.wins >= 5 && b.wins <= 10),
  ];
}

/** Whether the search for `q` returns exactly the fighters that match `truth`; and who is wrong. */
export function nlProblem(w: World, c: NlCase, found: BoxerFull[]): string | null {
  const want = new Set(w.boxers.filter((b) => b.bouts > 0 && c.truth(b, w)).map((b) => b.id));
  const got = new Set(found.map((b) => b.id));
  const extra = [...got].filter((id) => !want.has(id)).length, missing = [...want].filter((id) => !got.has(id)).length;
  return extra || missing ? `${got.size} returned, ${want.size} expected (${extra} too many, ${missing} missing)` : null;
}
